---
title: "CNNpolitics"
author: "余采蘋"
date: "2018年10月18日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## CNN Politics做tf-idf、針對Trump及GOP做tf-idf分析

1.先爬出CNN Politics 共54篇新聞內文，對文字做tf-idf處理   
2.篩選出同時出現出現"Trump" & "GOP(共和黨)" 的新聞 ，做tf-idf處理，並顯現圖表

```{r}
library(xml2)
library(rvest)
library(NLP)
library(tm)
library(tmcn)
library(htmltools)
library(readr)
library(tidytext)
library(wordcloud)
library(RColorBrewer)
library(Matrix)
library(rvest)
library(stringr)

#將CNN"politics"版第一頁每篇新聞html抓下來，存成txt檔
k <- readLines("file:///C:/Users/user/Desktop/NTU_COOL/week_5/news.txt" )


urlList <- list()
for(i in 2:99){
  url <- k[i] %>% as.character()
  urlList <- rbind(urlList, url)
}
urlList = unique(urlList)


```


讀取新聞內文，一次讀太多會被網站封鎖，所以設停頓3秒
```{r}
news.doc <- list()
for(url in urlList[2:55])
{
  print(url)
  html <- read_html(url) %>% html_nodes(".zn-body__paragraph") %>% html_text()
  texts = ""
  for (text in html)
  {
    texts = paste(texts, text)
  }
  news.doc <- rbind( news.doc, as.matrix(texts, sep=''))
  print("sleeping...")
  Sys.sleep(3)
  print("Im awake")
}
```

清理文字
```{r}
clean <- as.matrix(news.doc) 
clean <- as.character(clean)
clean <- Corpus(VectorSource(clean))



cleanc <-{
  cnn.space <-content_transformer(function(x , pattern ) gsub(pattern, " ", x))
  clean <- tm_map(clean, removePunctuation )
  clean <- tm_map(clean, removeWords, stopwords("english") )
  clean <- tm_map(clean, stripWhitespace )
  clean <- tm_map(clean, removeNumbers )
  clean <- tm_map (clean, stemDocument)
}
```

td-idf
```{r}
d.corpus <- Corpus(VectorSource(clean))
tdm <- TermDocumentMatrix(clean)
inspect(tdm)

#tf
tf <- (as.matrix(tdm))
#idf
idf <- log( ncol(tf) / ( 1 + rowSums(tf != 0) ) ) 

tf <- apply(tdm, 2, sum) # term frequency
idf <- function(word_doc){ log2( (length(word_doc)+1) / nnzero(word_doc) ) }
idf <- apply(tdm, 1, idf)
doc.tfidf <- as.matrix(tdm)
for(i in 1:nrow(tdm)){
  for(j in 1:ncol(tdm)){
    doc.tfidf[i,j] <- (doc.tfidf[i,j] / tf[j]) * idf[i]
  }
}

doc.tfidf
```

篩選出同時有"Trump" & "GOP(共和黨)"的文章，將tf-idf做rowsum並做出圖表
```{r }
cleanText = c()
for (t in clean)
{
  cleanText <- append(cleanText,t)
}
cleanText$language = NULL

GOPTexts = c()
for (count in str_count(cleanText, "Trump"))
{
  GOPTexts = append(GOPTexts, count != 0)
}

l = str_count(cleanText, "GOP")
for (i in 1:54)
{
  GOPTexts[i] = GOPTexts[i] || l[i]
}

newTFIDF = as.data.frame(doc.tfidf) 
select <- newTFIDF[,GOPTexts]
sums = rowSums(x=select)
selectr <-as.data.frame(sums)
selectr <- as.data.frame(selectr)
colnames(selectr)


```

遇到問題，一直無法將selectr跟Term轉成dataframe

