---
title: "ATP_RANk_RScrawler"
author: "余采蘋"
date: "2018年9月26日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## ATP_RANk_RScrawler:爬取當日最新ATP網球男單排名，並以表格呈現。表格中欄位分別為:選手、目前最新積分、比賽總次數
</font><br />

```{r url}
#設爬蟲頁面
library(xml2)
library(rvest)
tennis.source <- read_html("https://www.atpworldtour.com/en/rankings/singles")
```

<font size="4">set the rank(Top100)</font><br />
*網頁中的rank為cell是無法汲取，因此建立vector排序方式從1至100排列。
```{r }
tennis.rank <- c(1:100)
NROW(tennis.rank)
```

<font size="4">用SelectorGadget定位節點資訊並爬取球員名</font><br />
*使用NROW確認欄位數是否相同
```{r player}
tennis.player <- tennis.source %>% html_nodes(".player-cell a") %>% html_text()
NROW(tennis.player)  
```

<font size="4">用SelectorGadget定位節點資訊並爬取最新動態積分</font><br />
*使用NROW確認欄位數是否相同
```{r point}
tennis.point <- tennis.source %>% html_nodes(".points-cell a") %>% html_text() 
NROW(tennis.point)  
```

<font size="4">用SelectorGadget定位節點資訊並爬取比賽次數</font><br />
*使用NROW確認欄位數是否相同
```{r tourn}
tennis.tournplayed <- tennis.source %>% html_nodes(".tourn-cell a") %>% html_text()
NROW(tennis.tournplayed)
```

<font size="4">建立Dataframe</font><br />
*使用NROW確認欄位數是否相同
```{r }
df.tennis <- data.frame(tennis.rank,tennis.player,tennis.point,tennis.tournplayed)
df.tennis
```